services:
  - type: web
    name: picknmat
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: picknmat-db
          property: connectionString
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false

databases:
  - name: picknmat-db
    plan: free
    databaseName: picknmat
    user: picknmat_user
